#!/bin/bash

filepath=/home2_hn/QQF/SBU_YSU/wrfout
filename=(`ls $filepath/wrfout_d03*`)
num=${#filename[@]}

for ((i=0;i<num-1;i++))
do
	sed -i "5s/^.*.$/wrff1=addfile(\"\/home2_hn\/QQF\/SBU_YSU\/wrfout\/${filename[$i]/$filepath\//}\",\"r\")/" SCW.ncl
	sed -i "61s/^.*.$/res@tiMainString=\"${filename[$i]/$filepath\/wrfout_d03_/}\"/" SCW.ncl
	sed -i "64s/^.*.$/wks = gsn_open_wks(\"eps\", \"${filename[$i]/$filepath\/wrfout_d03_/}\")/" SCW.ncl
	ncl SCW.ncl
	mv ${filename[$i]/$filepath\/wrfout_d03_/}.eps /home2_hn/QQF/SBU_YSU/SCW/
done
