#!/bin/bash

filepathsa=/home2_hn/QQF/MCS/2014/MOR/wrfout
filenamesa=(`ls $filepathsa/wrfout_d03*`)
numsa=${#filenamesa[@]}

for ((ka=0;ka<numsa-1;ka++))
do
	sed -i "5s/^.*.$/wrff1=addfile(\"\/home2_hn\/QQF\/MCS\/2014\/MOR\/wrfout\/${filenamesa[$ka]/$filepathsa\//}\",\"r\")/" SCW.ncl
	sed -i "66s/^.*.$/res@tiMainString=\"${filenamesa[$ka]/$filepathsa\/wrfout_d03_/}\"/" SCW.ncl
	sed -i "69s/^.*.$/wks = gsn_open_wks(\"eps\", \"${filenamesa[$ka]/$filepathsa\/wrfout_d03_/}\")/" SCW.ncl
	ncl SCW.ncl
	mv ${filenamesa[$ka]/$filepathsa\/wrfout_d03_/}.eps /home2_hn/QQF/MCS/2014/MOR/SCW/
done
