#!/bin/bash
YEAR_START=2007
YEAR_END=2007
DAY_IN_MONTH_leap=(31 29 31 30 31 30 31 31 30 31 30 31)
DAY_IN_MONTH_noleap=(31 28 31 30 31 30 31 31 30 31 30 31)
DAYS=(01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31)
MONTHS=(01 02 03 04 05 06 07 08 09 10 11 12)
export NPOINT=7425
export NLEVEL=30
export TIMESTEP=0
WRFOUT_DIR="/home/QQF/WRF_COSP"
COSP_DIR="/home/QQF/Model/COSP"

for wrffile in `ls wrfout*`
do
    export FILEPATH=$WRFOUT_DIR/$wrffile
    ncl for_cosp.ncl
    mv test.nc ${wrffile}.nc
    rm -rf test.nc
done
mv *.nc $COSP_DIR/
cd $COSP_DIR/
for wrf_for_cosp in `ls wrfout*.nc`
do
    echo $wrf_for_cosp
    mv $wrf_for_cosp test.nc
    #sed -i "39s/^.*FINPUT.*$/  FINPUT='$wrf_for_cosp', ! List input NetCDF files/" $COSP_DIR/cosp_input_nl.txt
    $COSP_DIR/cosp_test
    rm -rf test.nc
    #mkdir ./outputs/${wrf_for_cosp/.nc/}
    #mv ./outputs/*.nc /outputs/${wrf_for_cosp/.nc/}
    mv outputs ${wrf_for_cosp/.nc/}
    mkdir outputs
done
